apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod
spec:
  containers:
    - image: nginx
      name: test-container
      volumeMounts:
        - mountPath: /var/log/nginx
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
      # directory location on local host        
        path: /tmp/nginx/
